# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.11', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.12', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.13', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.14', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.15', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  #},
  #:logserver => {
    #:box_name => "centos/8",
    #:net => [
			   #{ip: '192.168.90.16', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            #]
  #},
  #:backupserver => {
    #:box_name => "centos/8",
    #:net => [
			   #{ip: '192.168.90.17', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            #]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 512
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        #box.vm.provision "shell", inline: <<-SHELL
	      #mkdir -p ~root/.ssh
		  #cp ~vagrant/.ssh/auth* ~root/.ssh
        #SHELL
        
        case boxname.to_s
		
          when "nginx"
		    box.vm.network "forwarded_port", guest: 80, host: 8181
			box.vm.network "forwarded_port", guest: 22, host: 2301
			box.vm.provision "file", source: "config/nginx/nginx.conf", destination: "~/nginx.conf"
		    box.vm.provision "shell", path: "bash/nginx.sh"
			
          when "backend1"
		    box.vm.network "forwarded_port", guest: 80, host: 8282
			box.vm.network "forwarded_port", guest: 22, host: 2302
			box.vm.provision :file, source: "config/html", destination: "~/html"
		    box.vm.provision "shell", path: "bash/backend1.sh"
			
          when "backend2"
		    box.vm.network "forwarded_port", guest: 80, host: 8383
		    box.vm.network "forwarded_port", guest: 22, host: 2303
			box.vm.provision :file, source: "config/html2", destination: "~/html"
		    box.vm.provision "shell", path: "bash/backend2.sh"
			
          when "database1"
		    box.vm.network "forwarded_port", guest: 3306, host: 3306
			box.vm.network "forwarded_port", guest: 22, host: 2304
			box.vm.provision "file", source: "bash/msi.sh", destination: "~/msi.sh"
			box.vm.provision "file", source: "sql/project1.sql", destination: "~/project1.sql"
		    box.vm.provision "shell", path: "bash/database1.sh"
			
	      when "database2"
		    box.vm.network "forwarded_port", guest: 3306, host: 3307
		    box.vm.network "forwarded_port", guest: 22, host: 2305
			box.vm.provision "file", source: "bash/msi.sh", destination: "~/msi.sh"
			box.vm.provision "file", source: "sql/project1.sql", destination: "~/project1.sql"
		    box.vm.provision "shell", path: "bash/database2.sh"
			
		  #when "logserver"
		    #box.vm.network "forwarded_port", guest: 22, host: 2306
		    #box.vm.provision "shell", path: "bash/logserver.sh"
			
		  #when "backupserver"
		    #box.vm.network "forwarded_port", guest: 22, host: 2307
		    #box.vm.provision "shell", path: "bash/backupserver.sh"

        end
      end
  end
end
