# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.11', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.12', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.13', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backupserver => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.14', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.15', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.16', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :elasticsearch1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.17', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :elasticsearch2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.18', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :elasticsearch3 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.19', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :kibana => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :logstash1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.21', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :logstash2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.22', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
	config.vm.box_check_update = false
	
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        case boxname.to_s
		
          when "nginx"
			box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8181
			box.vm.network "forwarded_port", guest: 443, host: 4343
			box.vm.network "forwarded_port", guest: 22, host: 2301
			box.vm.provision "file", source: "config/nginx/nginx.conf", destination: "~/nginx.conf"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/nginx/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/nginx.sh"
			
		  when "backend1"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8282
			box.vm.network "forwarded_port", guest: 22, host: 2302
			box.vm.provision :file, source: "config/backend/html", destination: "~/html"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backend/filebeat1.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backend.sh"
			
          when "backend2"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8383
		    box.vm.network "forwarded_port", guest: 22, host: 2303
			box.vm.provision :file, source: "config/backend/html", destination: "~/html"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backend/filebeat2.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backend.sh"
			
		  when "backupserver"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2304
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backupserver/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backupserver.sh"

          when "database1"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 512
			end
			box.vm.network "forwarded_port", guest: 22, host: 2305
			box.vm.provision "file", source: "sql/project1.sql", destination: "~/project1.sql"
			box.vm.provision "file", source: "bash/backup.sh", destination: "~/backup.sh"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/database/filebeat1.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/database.sh"
			
	      when "database2"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 512
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2306
			box.vm.provision "file", source: "bash/backup.sh", destination: "~/backup.sh"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/database/filebeat2.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/database.sh"	  

		  when "elasticsearch1"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 3072
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2307
			box.vm.network "forwarded_port", guest: 9200, host: 9200   # Порт для Elasticsearch
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/elasticsearch/elasticsearch1.yml", destination: "~/elasticsearch.yml"
			box.vm.provision "file", source: "config/filebeat/elasticsearch/filebeat1.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/elasticsearch.sh"
			
			when "elasticsearch2"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 3072
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2308
			box.vm.network "forwarded_port", guest: 9200, host: 9201   # Порт для Elasticsearch
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/elasticsearch/elasticsearch2.yml", destination: "~/elasticsearch.yml"
			box.vm.provision "file", source: "config/filebeat/elasticsearch/filebeat2.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/elasticsearch.sh"
			
			when "elasticsearch3"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 3072
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2309
			box.vm.network "forwarded_port", guest: 9200, host: 9202   # Порт для Elasticsearch
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/elasticsearch/elasticsearch3.yml", destination: "~/elasticsearch.yml"
			box.vm.provision "file", source: "config/filebeat/elasticsearch/filebeat3.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/elasticsearch.sh"
			
			when "kibana"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 1024
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2310
			box.vm.network "forwarded_port", guest: 5601, host: 5601   # Порт для Kibana
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/kibana/kibana.yml", destination: "~/kibana.yml"
			box.vm.provision "file", source: "config/kibana/heartbeat.yml", destination: "~/heartbeat.yml"
			box.vm.provision "file", source: "config/filebeat/kibana/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/kibana.sh"
			
			when "logstash1"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 2048
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2311
			box.vm.provision :file, source: "config/logstash/conf.d", destination: "~/conf.d"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/logstash/pipelines.yml", destination: "~/pipelines.yml"
			box.vm.provision "file", source: "config/filebeat/logstash/filebeat1.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/logstash.sh"
			
			when "logstash2"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 2048
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2312
			box.vm.provision :file, source: "config/logstash/conf.d", destination: "~/conf.d"
			box.vm.provision "file", source: "config/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/logstash/pipelines.yml", destination: "~/pipelines.yml"
			box.vm.provision "file", source: "config/filebeat/logstash/filebeat2.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/logstash.sh"
			
        end
      end
  end
end
