# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.11', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.12', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backend2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.13', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :backupserver => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.14', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database1 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.15', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :database2 => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.16', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  },
  :logserver => {
    :box_name => "centos/8",
    :net => [
			   {ip: '192.168.90.17', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-net"}
            ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
	config.vm.box_check_update = false
	
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        #box.vm.provision "shell", inline: <<-SHELL
	      #mkdir -p ~root/.ssh
		  #cp ~vagrant/.ssh/auth* ~root/.ssh
        #SHELL
        
        case boxname.to_s
		
          when "nginx"
			box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8181
			box.vm.network "forwarded_port", guest: 22, host: 2301
			box.vm.provision "file", source: "config/nginx/nginx.conf", destination: "~/nginx.conf"
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/nginx/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/nginx.sh"
			
		  when "backend1"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8282
			box.vm.network "forwarded_port", guest: 22, host: 2302
			box.vm.provision :file, source: "config/backend/html", destination: "~/html"
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backend1/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backend.sh"
			
          when "backend2"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 80, host: 8383
		    box.vm.network "forwarded_port", guest: 22, host: 2303
			box.vm.provision :file, source: "config/backend/html2", destination: "~/html"
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backend2/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backend.sh"
			
		  when "backupserver"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 256
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2304
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/backupserver/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/backupserver.sh"

          when "database1"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 512
			end
			box.vm.network "forwarded_port", guest: 22, host: 2305
			box.vm.provision "file", source: "sql/project1.sql", destination: "~/project1.sql"
			box.vm.provision "file", source: "bash/backup_sql_1.sh", destination: "~/backup.sh"
			box.vm.provision "file", source: ".vagrant/machines/backupserver/virtualbox/private_key", destination: "~/backup_private_key"
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/database1/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/database1.sh"
			
	      when "database2"
		    box.vm.provider "virtualbox" do |v|
			  v.memory = 512
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2306
			box.vm.provision "file", source: "bash/backup_sql_2.sh", destination: "~/backup.sh"
			box.vm.provision "file", source: ".vagrant/machines/backupserver/virtualbox/private_key", destination: "~/backup_private_key"
			box.vm.provision "file", source: ".vagrant/machines/database1/virtualbox/private_key", destination: "~/database1_private_key"
			box.vm.provision "file", source: "config/logserver/yum.repos.d/elasticsearch.repo", destination: "~/elasticsearch.repo"
			box.vm.provision "file", source: "config/filebeat/database2/filebeat.yml", destination: "~/filebeat.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/database2.sh"	  

		  when "logserver"
		    box.vm.provider "virtualbox" do |v| 
			  v.memory = 3072
			end
		    box.vm.network "forwarded_port", guest: 22, host: 2307
			box.vm.network "forwarded_port", guest: 9200, host: 9200   # Порт для Elasticsearch
			box.vm.network "forwarded_port", guest: 5601, host: 5601   # Порт для Kibana
			box.vm.provision :file, source: "config/logserver", destination: "~/logserver"
			box.vm.provision "file", source: "config/logserver/logstash/pipelines.yml", destination: "~/pipelines.yml"
			box.vm.provision "shell", path: "bash/all_setup.sh"
		    box.vm.provision "shell", path: "bash/logserver.sh"
			
        end
      end
  end
end
