#server.host: "192.168.90.17"
server.host: "0.0.0.0"

server.publicBaseUrl: "http://192.168.90.17:5601"

elasticsearch.hosts: ["https://192.168.90.17:9200"]

elasticsearch.username: "kibana_system"
elasticsearch.password: "123456"

elasticsearch.ssl.certificateAuthorities: [ "/etc/kibana/certs/http_ca.crt" ]

logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders:
      - default
      - file

pid.file: /run/kibana/kibana.pid
