# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
  end

  config.vm.define "serverras" do |serverras|
    #serverras.vm.network "private_network", ip: "192.168.10.10"
	serverras.vm.network "public_network", ip: "192.168.100.239", bridge: "enp3s0"
    serverras.vm.hostname = "serverras"
  end

end
