filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  exclude_files: [".gz$"]
  
  fields:
    type: nginx_access
    #service: nginx_access
  fields_under_root: true
  scan_frequency: 5s

- type: log
  enabled: true
  paths:
    - /var/log/nginx/error.log
  exclude_files: [".gz$"]
      
  fields:
    type: nginx_error
    #service: nginx_access
  fields_under_root: true
  scan_frequency: 5s

#-----------------------------------

output.logstash:
  hosts: ["192.168.90.17:5041"]
