Vagrant.configure("2") do |config|
  
    config.vm.box_check_update = false
	
	
	
	config.vm.define "web" do |web|
		web.vm.box = "generic/ubuntu2004"
		web.vm.communicator = "ssh"
		web.vm.hostname = "web"
		web.vm.network "public_network", ip: "192.168.100.208", bridge: "enp3s0"

		web.vm.provision "shell", path: "bash_web.sh"

		web.vm.provider "virtualbox" do |vb|
			vb.cpus =1
			vb.gui = true
			vb.memory = "1024"
		end
	end
	
	
	
	config.vm.define "log" do |log|
		log.vm.box = "generic/ubuntu2004"
		log.vm.communicator = "ssh"
		log.vm.hostname = "log"
		log.vm.network "public_network", ip: "192.168.100.209", bridge: "enp3s0"

		log.vm.provision "shell", path: "bash_log.sh"

		log.vm.provider "virtualbox" do |vb|
			vb.cpus =1
			vb.gui = true
			vb.memory = "1024"
		end
	end
	
	
	
end