filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/audit/audit.log
  exclude_files: [".gz$"]
  
  fields:
    type: audit_elasticsearch1
    #service: nginx_access
  fields_under_root: true
  scan_frequency: 5s

#-----------------------------------

output.logstash:
  hosts: ["192.168.90.21:5047", "192.168.90.22:5047"]
