# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.10.10"
    server.vm.hostname = "server.loc"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.10.20"
    client.vm.hostname = "client.loc"
  end

end
