node.name: logserver

path.data: /var/lib/elasticsearch

path.logs: /var/log/elasticsearch

network.host: 192.168.90.17

# Oдноузловой кластер
#discovery.type: single-node

xpack.security.enabled: true

xpack.security.enrollment.enabled: true

xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12

cluster.initial_master_nodes: ["logserver"]

http.host: 0.0.0.0
