# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.define "server.test.local" do |s|
    s.vm.hostname = 'server.test.local'
    s.vm.network "private_network", ip: "192.168.50.10"
	s.vm.network "public_network", ip: "192.168.100.241", bridge: "enp3s0"
	s.vm.network "forwarded_port", guest: 443, host: 4949
	s.vm.provider :virtualbox do |v|
		v.name = "server.test.local"
		v.memory = 4096
    end

	s.vm.provision "ansible" do |ansible|
        ansible.playbook = "server.yml"
	end
	
  end
  
  config.vm.define "client1.test.local", primary: true do |c|
    c.vm.hostname = 'client1.test.local'
    c.vm.network "private_network", ip: "192.168.50.11"
	c.vm.provider :virtualbox do |v|
		v.name = "client1.test.local"
		v.memory = 512

    end

	c.vm.provision "ansible" do |ansible|
        ansible.playbook = "client1.yml"
	end
	
  end

  
end
