
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2004"
  config.vm.box_check_update = false

  config.vm.define "server1" do |server1|
    server1.vm.provider "virtualbox" do |vb|
	  vb.cpus = 1
      vb.memory = "1024"
    end

	server1.vm.hostname = "server1"
    server1.vm.communicator = "ssh"
	server1.vm.host_name = 'server1'
	#server1.vm.network "public_network", type: "dhcp"
	server1.vm.network "public_network", ip: "192.168.100.201"
  end

  config.vm.define "server2" do |server2|
    server2.vm.provider "virtualbox" do |vb|
	  vb.cpus = 1
      vb.memory = "1024"
    end

	server2.vm.hostname = "server2"
    server2.vm.communicator = "ssh"
	server2.vm.host_name = 'server2'
	#server2.vm.network "public_network", type: "dhcp"
	server2.vm.network "public_network", ip: "192.168.100.202"
  end

end