filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/logstash/logstash-plain.log
  exclude_files: [".gz$"]
  
  fields:
    type: logstash2
  fields_under_root: true
  scan_frequency: 5s

#-----------------------------------

output.logstash:
  hosts: ["192.168.90.21:5052", "192.168.90.22:5052"]
