
server.host: "0.0.0.0"
server.publicBaseUrl: "http://192.168.90.20:5601"
elasticsearch.hosts: ["http://192.168.90.17:9200", "http://192.168.90.18:9200", "http://192.168.90.19:9200"]

logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders:
      - default
      - file

pid.file: /run/kibana/kibana.pid
