# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :net => [
			   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"}
            ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :net => [
			   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
			   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
			   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
			   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"}
            ]
  },
  :centralServer => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"}
            ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.0.3', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"}
            ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
		  cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
		
          when "inetRouter"
		    box.vm.provision "shell", path: "inetRouter.sh"
			
          when "centralRouter"
		    box.vm.provision "shell", path: "centralRouter.sh"
			
          when "centralServer"
			box.vm.provision "shell", path: "centralServer.sh"
			
          when "inetRouter2"
		    box.vm.network "forwarded_port", guest: 80, host: 8080
		    box.vm.provision "shell", path: "inetRouter2.sh"

        end
      end
  end
end
